## API CLIENTE - GET

GET http://localhost:8080/api/v1/clientes

## API CLIENTE - PUT

PUT http://localhost:8080/api/v1/clientes/1
Content-Type: application/json

{
    "nome": "rhu",
    "email":"rhuanjosevoltolini@gmail.com",
    "endereco":"rua Avencal 399",
    "telefone":"47996540247",
    "dataNascimento": "2025-04-15"
}